PROJ = vga_pong
SRC += top.v
SRC += pong_top.v
SRC += vga_sync_pulse.v
SRC += vga_sync_porch.v
SRC += sync_count.v
SRC += pong_ball_control.v
SRC += pong_paddle_control.v
SRC += debounce_switch.v

all: $(PROJ).bin
include ../Makefile.beaglewire
